services:
    wobblecode_notification.invitation_manager:
        class: WobbleCode\NotificationBundle\Manager\InvitationManager
        parent: wobblecode_manager.document_manager
        calls:
            - [setDocument, ["WobbleCodeNotificationBundle:Invitation"]]
    wobblecode_notification.notification_manager:
        class: WobbleCode\NotificationBundle\Manager\NotificationManager
        parent: wobblecode_manager.document_manager
        calls:
            - [setTokenStorage, ["@security.token_storage"]]
            - [setDocument, ["WobbleCodeNotificationBundle:Notification"]]
    wobblecode_notification.subscription_manager:
        class: WobbleCode\NotificationBundle\Manager\SubscriptionManager
        parent: wobblecode_manager.document_manager
        calls:
            - [setRoleHierarchy, ["@security.role_hierarchy"]]
            - [setDocument, ["WobbleCodeNotificationBundle:Subscription"]]
    wobblecode_notification.event_manager:
        class: WobbleCode\NotificationBundle\Manager\EventManager
        parent: wobblecode_manager.document_manager
        calls:
            - [setDocument, ["WobbleCodeNotificationBundle:Event"]]
    wobblecode_notification.channel_manager:
        class: WobbleCode\NotificationBundle\Manager\ChannelManager
        parent: wobblecode_manager.document_manager
        calls:
            - [setDocument, ["WobbleCodeNotificationBundle:Channel"]]
    wobblecode_notification.notificator:
        class: WobbleCode\NotificationBundle\Service\Notificator
        arguments:
            - "@doctrine_mongodb.odm.document_manager"
            - "@event_dispatcher"
            - "@wobblecode_notification.subscription_manager"
        calls:
            - [setContainer, ["@service_container"]]

    wobblecode_notification.notification_subscriber:
        class: WobbleCode\NotificationBundle\EventListener\NotificationSubscriber
        arguments:
            - "@doctrine_mongodb.odm.document_manager"
            - "@wobblecode_notification.notificator"
        tags:
            -  { name: kernel.event_subscriber }
    wobblecode_notification.twig.notification_extension:
        class: WobbleCode\NotificationBundle\Twig\NotificationExtension
        arguments:
            - "@wobblecode_notification.notification_manager"
            - "@security.context"
        tags:
            -  { name: twig.extension, alias: notification_extension }

    #Channels
    wobblecode_notification.channel.ui:
        class: WobbleCode\NotificationBundle\Channel\UiChannel
        arguments:
            - "@wobblecode_notification.notification_manager"
            - "@twig"

    wobblecode_notification.channel.mail:
        class: WobbleCode\NotificationBundle\Channel\MailChannel
        arguments:
            - "@instasent_resque.resque"
            - "@twig"
            - "@swiftmailer.mailer.default"
            - "@swiftmailer.mailer.default.transport.real"
